[package]
name = "octez"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
license-file.workspace = true
description = "Bindings to Octez (Tezos) binaries"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
hex.workspace = true
http.workspace = true
jstz_crypto = {path = "../jstz_crypto"}
regex.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
signal-hook.workspace = true
tempfile.workspace = true
tezos-smart-rollup-encoding.workspace = true
tezos_crypto_rs.workspace = true
tokio.workspace = true
