blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¨â€âš–ï¸ `jstz` slack
    url: https://tezos-dev.slack.com/archives/C061SSDBN69
    about: If you have a question about `jstz`, please ask on our slack channel
