[package]
name = "jstz_cli"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jstz_kernel.workspace = true
jstz_crypto.workspace = true
jstz_proto.workspace = true
jstz_core.workspace = true
jstz_api.workspace = true
clap = { version = "^4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bs58 = "0.5"
hex = "0.4"
dirs = "3.0"
nix = "^0.20.2"
http = "0.2.9"
fs_extra = "1.2"
anyhow = "1.0.75"
daemonize = "0.5.0"
tempfile = "3.8.0"
signal-hook = "0.3.17"
boa_engine = "0.17.0"
rustyline = "12.0.0"
tezos-smart-rollup.workspace = true
tezos-smart-rollup-mock.workspace = true
tezos-smart-rollup-installer-config.workspace = true
serde_yaml = "0.8"
tezos_crypto_rs = "0.5.2"
sha2 = "0.9"
rand = "0.8"
tiny-bip39 = "1.0.0"
bincode = "1.3.3"
reqwest = { version = "0.11.22", features = ["json"] }
tokio = { version = "1.33.0", features = ["full"] }
derive_more = "0.99.17"
url = "2.2.2"

boa_gc = { git = "https://github.com/trilitech/boa.git", branch = "ajob410@create-realm-with-default-globals" }
reqwest-eventsource = "0.5.0"
futures-util = "0.3.29"

[[bin]]
name = "jstz"
path = "src/main.rs"
