[package]
name = "jstz_crypto"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
tezos_crypto_rs = { version = "0.5.0", default-features = false }
derive_more = "0.99.17"
serde = "1.0.185"
