[[bin]]
name = "main_app"
path = "src/main.rs"

[[bin]]
name = "sandbox_initializer"
path = "src/sandbox_initializer.rs"

[package]
name = "jstz-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nom = "7"
bs58 = "0.4"
hex = "0.4"
ctrlc = "3.1"
tempfile = "3.2"
dirs = "3.0"
nix = "0.20"

[workspace]